### ISSUE TITLE
Cellular: Export to ZIP does not work in Chrome

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#47] opened 2015-05-14 05:02 UTC
Cellular: Export to ZIP does not work in Chrome (only works in Firefox).

**Comment by aidanlane** [comment] 2015-05-15 09:43
Require shift button to be pressed to see this option in the file menu? Alert user if not running Firefox?

**Comment by Craxic** [comment] 2015-05-16 08:18
@mciotola: Can I ask how you are running Cellular? I cannot even get the ZIP working in Firefox. I just want to make sure I haven't changed something.

Thanks!

**Comment by mciotola** [comment] 2015-05-18 01:30
I am running Cellular on OSX 10.9.5 on Firefox 38.0.1 (which changed from
37).

I use this URL:

http://aidanlane.github.io/snapapps/cellular.html

The file gets saved with an archaic name such as "xRJ6oR5Q.zip".

**Comment by Craxic** [comment] 2015-05-18 07:50
Hi Mark,

Yes this is the intended behaviour. Unfortunately it isn't possible for us to specify a filename for download as far as I am aware.

It should hopefully work on Chrome (although mine runs out of memory :(). Let me know how it goes.

Thanks.

**Comment by mciotola** [comment] 2015-05-18 20:56
Hi Matt,

It still won't work for me on Chrome. I still get the "Aw, Snap!" error
page.


Mark

**Comment by aidanlane** [comment] 2015-05-19 01:21
@Craxic, can we go with this plan then: "Require shift button to be pressed (like Edgy does) to see this option in the file menu? Alert user if not running Firefox?"

**Comment by Craxic** [comment] 2015-05-23 05:00
Fixed in Chrome.

**Comment by aidanlane** [comment] 2015-05-25 05:31
Works great on Chrome now too, thanks Matt!

Unfortunately it doesn't work on Safari (at least in 8.0.6).

Therefore, can we go with this plan then: Require shift button to be pressed (like Edgy does) to see this option in the file menu? Alert user if not running Firefox or Chrome?

Thanks again for all your help!

**Closed** 2015-06-01 08:20 UTC

**Comment by aidanlane** [comment] 2015-06-01 09:22
Great, thanks!!
